In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset = pd.read_csv("dataset full 9f new.csv")

In [2]:
dataset.shape

(222552, 10)

# Dataframe processed

In [3]:
# input
x = dataset.iloc[:, [0,1,2,4,5,7,8]].values
  
# output
y = dataset.iloc[:, -1].values


In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state=0)

In [5]:
X_train
# X_train.shape

array([[2.89365195e+00, 3.00000000e+00, 3.56449376e+01, ...,
        7.21000000e+02, 1.33148405e-01, 9.16666667e-02],
       [2.12375533e+00, 1.20000000e+01, 4.47368421e+01, ...,
        4.94000000e+02, 1.76113360e-01, 6.69371197e-02],
       [1.36938683e+00, 4.00000000e+00, 5.20547945e+01, ...,
        7.30000000e+01, 0.00000000e+00, 2.77777778e-02],
       ...,
       [2.02911217e+00, 1.00000000e+00, 4.04958678e+01, ...,
        1.21000000e+02, 0.00000000e+00, 8.33333333e-02],
       [1.68049617e+00, 2.10000000e+01, 5.12820513e+01, ...,
        3.12000000e+02, 3.26923077e-01, 6.10932476e-02],
       [1.95496778e+00, 1.34000000e+02, 4.22205246e+01, ...,
        7.85400000e+03, 5.32849503e-01, 6.76174710e-02]])

In [110]:
X_test
# X_test.shape

array([[9.73877217e-01, 5.80000000e+01, 6.71383648e+01, ...,
        6.36000000e+02, 1.08490566e-01, 3.14960630e-02],
       [1.32475530e+00, 1.00000000e+00, 4.16666667e+01, ...,
        2.40000000e+01, 0.00000000e+00, 4.34782609e-02],
       [1.17262503e+00, 1.00000000e+02, 5.90985915e+01, ...,
        3.55000000e+03, 2.06197183e-01, 3.15581854e-02],
       ...,
       [1.28090610e+00, 1.90000000e+01, 5.47872340e+01, ...,
        1.88000000e+02, 7.97872340e-02, 6.41711230e-02],
       [2.01870407e+00, 3.00000000e+00, 3.82608696e+01, ...,
        1.15000000e+02, 7.82608696e-02, 9.64912281e-02],
       [1.24221418e+00, 1.07000000e+02, 6.35437882e+01, ...,
        9.82000000e+02, 1.58859470e-01, 3.36391437e-02]])

In [111]:
# from sklearn.preprocessing import StandardScaler
# sc_x = StandardScaler()
# X_train = sc_x.fit_transform(X_train) 
# X_test = sc_x.transform(X_test)
  
# print (X_train[0:10, :])

In [112]:
X_train.shape

(166914, 7)

# Logistic Regression model

In [6]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state = 2)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

/home/pc/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [7]:
# from sklearn.model_selection import cross_val_score

# scores = cross_val_score(classifier, x, y, cv=5)
# print("Logistic Regression Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

In [8]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[27265   509]
 [ 1248 26616]]


In [9]:

from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.9684208634386571


In [10]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)


Test set RMSE: 0.17770519565095155


# Random Forest

In [11]:
from sklearn.ensemble import RandomForestClassifier

random_classifier = RandomForestClassifier(n_estimators=50, random_state=0)
random_classifier.fit(X_train, y_train)

y_pred = random_classifier.predict(X_test)

In [12]:
# from sklearn.model_selection import cross_val_score

# scores = cross_val_score(random_classifier, x, y, cv=5)
# print("Logistic Regression Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

In [13]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[27375   399]
 [  429 27435]]


In [14]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.9851180847622129


In [15]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)


Test set RMSE: 0.12199145559336164


# Support Vector Machine

In [ ]:
from sklearn.svm import SVC

svm_classifier = SVC(kernel='linear', random_state=0)
svm_classifier.fit(X_train, y_train)

y_pred = svm_classifier.predict(X_test)

In [ ]:
# from sklearn.model_selection import cross_val_score

# scores = cross_val_score(svm_classifier, x, y, cv=5)
# print("Logistic Regression Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

In [ ]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

In [ ]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)

# Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB

nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)

y_pred = nb_classifier.predict(X_test)

In [ ]:
# from sklearn.model_selection import cross_val_score

# scores = cross_val_score(nb_classifier, x, y, cv=5)
# print("Logistic Regression Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

In [ ]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

In [ ]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)

# Pickle formation

In [16]:
import pickle


In [17]:

with open('lr_model 7f new.pkl','wb') as files:
    pickle.dump(classifier,files)

In [18]:

with open('random_model 7f new.pkl','wb') as files:
    pickle.dump(random_classifier,files)

In [ ]:

with open('nb_model 7f new.pkl','wb') as files:
    pickle.dump(nb_classifier,files)

In [ ]:

with open('svm_model 7f new.pkl','wb') as files:
    pickle.dump(svm_classifier,files)