In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset = pd.read_csv("dataset full 7f.csv")

In [4]:
dataset.shape

(222552, 8)

# Dataframe processed

In [5]:
# input
x = dataset.iloc[:, :-1].values
  
# output
y = dataset.iloc[:, -1].values


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state=0)

In [7]:
X_train
# X_train.shape

array([[1.37326494e+00, 1.30000000e+01, 5.65349544e+01, ...,
        3.29000000e+02, 3.37386018e-01, 2.74390244e-02],
       [2.01395363e+00, 2.00000000e+01, 4.42844284e+01, ...,
        2.22200000e+03, 3.78037804e-02, 6.93381360e-02],
       [1.66767601e+00, 5.50000000e+01, 4.57312546e+01, ...,
        1.34700000e+03, 3.60801782e-01, 7.80089153e-02],
       ...,
       [1.91702925e+00, 2.10000000e+01, 3.88915663e+01, ...,
        2.07500000e+03, 4.51084337e-01, 8.63066538e-02],
       [1.70155488e+00, 4.60000000e+01, 4.30690073e+01, ...,
        3.30400000e+03, 4.12227603e-01, 7.44777475e-02],
       [1.52110644e+00, 2.10000000e+01, 5.05037783e+01, ...,
        7.94000000e+02, 7.55667506e-01, 5.04413619e-02]])

In [8]:
X_test
# X_test.shape

array([[1.24481294e+00, 2.00000000e+00, 5.33333333e+01, ...,
        7.50000000e+01, 7.60000000e-01, 4.05405405e-02],
       [2.25328183e+00, 2.80000000e+01, 3.89920424e+01, ...,
        1.88500000e+03, 1.25729443e-01, 7.32484076e-02],
       [1.53606352e+00, 1.10000000e+01, 5.09090909e+01, ...,
        1.65000000e+02, 2.36363636e-01, 7.92682927e-02],
       ...,
       [1.28706868e+00, 6.10000000e+01, 5.42894565e+01, ...,
        1.52700000e+03, 6.24754420e-01, 4.58715596e-02],
       [1.18660326e+00, 1.58000000e+02, 5.80474934e+01, ...,
        6.82200000e+03, 8.20580475e-01, 3.40126081e-02],
       [1.47633422e+00, 0.00000000e+00, 3.91304348e+01, ...,
        2.30000000e+01, 0.00000000e+00, 9.09090909e-02]])

In [7]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train) 
X_test = sc_x.transform(X_test)
  
print (X_train[0:10, :])

[[-0.46033852 -0.9892416  -0.42553402 -0.5403317  -1.12030976]
 [-0.40447066  0.69855764 -0.24466744 -0.40697133  0.71337109]
 [-0.31637135  0.21978883 -0.56964917 -0.40697133  0.76296711]
 [ 0.28958006  2.38392194  0.15257833  1.26955903  0.01367883]
 [ 0.31751399 -0.42820634 -0.21576182 -0.12119911  1.83582113]
 [-0.35934662 -0.28079115 -0.41686233 -0.57843466 -0.13124486]
 [-0.47323111  0.21453788 -0.71004788 -0.71179503  0.10160768]
 [ 0.20577827 -0.80806667 -0.10633341 -0.29266244 -0.15482279]
 [-0.40017314  0.6038571  -0.47302182 -0.59748614 -0.42677012]
 [-0.34430528  0.47506747 -0.04108931 -0.29266244 -0.59485872]]


In [8]:
X_train.shape

(87034, 5)

# Logistic Regression model

In [6]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state = 2)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

/home/pc/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [14]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(classifier, x, y, cv=5)
print("Logistic Regression Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Logistic Regression Accuracy: 0.86 (+/- 0.00)


In [15]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[13482  1017]
 [ 3032 11481]]


In [7]:

from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.9674503037492361


In [17]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)


Test set RMSE: 0.3735812354405951


# Random Forest

In [9]:
from sklearn.ensemble import RandomForestClassifier

random_classifier = RandomForestClassifier(n_estimators=50, random_state=0)
random_classifier.fit(X_train, y_train)

y_pred = random_classifier.predict(X_test)

In [10]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(random_classifier, x, y, cv=5)
print("Logistic Regression Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Logistic Regression Accuracy: 0.98 (+/- 0.00)


In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[27201   409]
 [  446 27582]]


In [16]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.9846328049175024


In [13]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)


Test set RMSE: 0.12396449121622519


# Support Vector Machine

In [ ]:
from sklearn.svm import SVC

svm_classifier = SVC(kernel='linear', random_state=0)
svm_classifier.fit(X_train, y_train)

y_pred = svm_classifier.predict(X_test)

In [ ]:
# from sklearn.model_selection import cross_val_score

# scores = cross_val_score(svm_classifier, x, y, cv=5)
# print("Logistic Regression Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

In [ ]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

In [ ]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)

# Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB

nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)

y_pred = nb_classifier.predict(X_test)

In [29]:
# from sklearn.model_selection import cross_val_score

# scores = cross_val_score(nb_classifier, x, y, cv=5)
# print("Logistic Regression Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

In [30]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[13882   617]
 [ 5315  9198]]


In [ ]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

In [32]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)

Test set RMSE: 0.4521804032186841


# Pickle formation

In [14]:
import pickle


In [ ]:

with open('lr_model.pkl','wb') as files:
    pickle.dump(classifier,files)

In [17]:

with open('random_model.pkl','wb') as files:
    pickle.dump(random_classifier,files)

In [ ]:

with open('nb_model.pkl','wb') as files:
    pickle.dump(nb_classifier,files)

In [ ]:

with open('svm_model.pkl','wb') as files:
    pickle.dump(svm_classifier,files)