In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset = pd.read_csv("datasheet_ver2.csv")

In [2]:
dataset

ORF Length  GC Content  Transcript Length  CpG Island  Ficket score  \
0            138.0   38.569425              713.0         5.0      1.172722   
1            189.0   48.032787             1220.0        41.0      1.168862   
2            171.0   53.114754              610.0        23.0      0.949387   
3            537.0   41.805556              720.0        10.0      1.154088   
4           1218.0   47.773502             1819.0        33.0      0.880220   
...            ...         ...                ...         ...           ...   
116041       141.0   51.027811              827.0        33.0      1.316544   
116042       333.0   36.901654             1149.0        11.0      0.853603   
116043       225.0   51.943463             1415.0        28.0      1.095665   
116044       276.0   48.976608              684.0        19.0      1.473068   
116045       315.0   42.086753              853.0        14.0      0.983502   

         Coding Potential  
0                     0.0  
1                     0.0  
2                     0.0  
3                     1.0  
4                     1.0  
...                   ...  
116041                0.0  
116042                1.0  
116043                0.0  
116044                1.0  
116045                1.0  

[116046 rows x 6 columns]

# Dataframe processed

In [3]:
# input
x = dataset.iloc[:, :-1].values
  
# output
y = dataset.iloc[:, -1].values


In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state=0)

In [5]:
X_train
# X_train.shape

array([[1.3800000e+02, 4.0196078e+01, 9.1800000e+02, 1.3000000e+01,
        6.9923000e-01],
       [2.1600000e+02, 5.3023599e+01, 1.3560000e+03, 2.0000000e+01,
        1.4717300e+00],
       [3.3900000e+02, 4.9384886e+01, 5.6900000e+02, 2.0000000e+01,
        1.4926240e+00],
       ...,
       [4.3800000e+02, 5.6365884e+01, 8.0900000e+02, 1.5000000e+01,
        9.4130200e-01],
       [3.3900000e+02, 4.3225806e+01, 1.5500000e+03, 1.3000000e+01,
        1.2447110e+00],
       [2.3700000e+02, 4.2393509e+01, 1.4790000e+03, 3.0000000e+01,
        1.2684710e+00]])

In [6]:
X_test
# X_test.shape

array([[1.5900000e+03, 4.6102450e+01, 1.7960000e+03, 4.1000000e+01,
        1.4963480e+00],
       [3.5400000e+02, 4.6153846e+01, 8.3200000e+02, 5.0000000e+00,
        1.0151300e+00],
       [9.5100000e+02, 3.7495623e+01, 1.9989000e+04, 1.7500000e+02,
        8.3003000e-01],
       ...,
       [2.4600000e+02, 5.8788774e+01, 6.7700000e+02, 2.6000000e+01,
        7.2770100e-01],
       [3.0600000e+02, 5.5965293e+01, 4.6100000e+02, 2.2000000e+01,
        2.0905180e+00],
       [4.2900000e+02, 4.8682448e+01, 2.2390000e+03, 3.1000000e+01,
        1.1812980e+00]])

In [7]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train) 
X_test = sc_x.transform(X_test)
  
print (X_train[0:10, :])

[[-0.46033852 -0.9892416  -0.42553402 -0.5403317  -1.12030976]
 [-0.40447066  0.69855764 -0.24466744 -0.40697133  0.71337109]
 [-0.31637135  0.21978883 -0.56964917 -0.40697133  0.76296711]
 [ 0.28958006  2.38392194  0.15257833  1.26955903  0.01367883]
 [ 0.31751399 -0.42820634 -0.21576182 -0.12119911  1.83582113]
 [-0.35934662 -0.28079115 -0.41686233 -0.57843466 -0.13124486]
 [-0.47323111  0.21453788 -0.71004788 -0.71179503  0.10160768]
 [ 0.20577827 -0.80806667 -0.10633341 -0.29266244 -0.15482279]
 [-0.40017314  0.6038571  -0.47302182 -0.59748614 -0.42677012]
 [-0.34430528  0.47506747 -0.04108931 -0.29266244 -0.59485872]]


In [8]:
X_train.shape

(87034, 5)

# Logistic Regression model

In [13]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state = 2)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

In [14]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(classifier, x, y, cv=5)
print("Logistic Regression Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Logistic Regression Accuracy: 0.86 (+/- 0.00)


In [15]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[13482  1017]
 [ 3032 11481]]


In [16]:

from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.8604370605266786


In [17]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)


Test set RMSE: 0.3735812354405951


# Random Forest

In [18]:
from sklearn.ensemble import RandomForestClassifier

random_classifier = RandomForestClassifier(n_estimators=50, random_state=0)
random_classifier.fit(X_train, y_train)

y_pred = random_classifier.predict(X_test)

In [19]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(random_classifier, x, y, cv=5)
print("Logistic Regression Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Logistic Regression Accuracy: 0.89 (+/- 0.00)


In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[13301  1198]
 [ 2012 12501]]


In [21]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.8893561284985523


In [22]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)


Test set RMSE: 0.3326317355596842


# Support Vector Machine

In [23]:
from sklearn.svm import SVC

svm_classifier = SVC(kernel='linear', random_state=0)
svm_classifier.fit(X_train, y_train)

y_pred = svm_classifier.predict(X_test)

In [24]:
# from sklearn.model_selection import cross_val_score

# scores = cross_val_score(svm_classifier, x, y, cv=5)
# print("Logistic Regression Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

In [25]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[13493  1006]
 [ 3012 11501]]


In [26]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.8615055838963188


In [27]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)

Test set RMSE: 0.37214837914960913


# Naive Bayes

In [28]:
from sklearn.naive_bayes import GaussianNB

nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)

y_pred = nb_classifier.predict(X_test)

In [29]:
# from sklearn.model_selection import cross_val_score

# scores = cross_val_score(nb_classifier, x, y, cv=5)
# print("Logistic Regression Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

In [30]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[13882   617]
 [ 5315  9198]]


In [31]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.7955328829449883


In [32]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)

Test set RMSE: 0.4521804032186841


# Pickle formation

In [33]:
import pickle

with open('lr_model.pkl','wb') as files:
    pickle.dump(classifier,files)
with open('random_model.pkl','wb') as files:
    pickle.dump(random_classifier,files)
with open('nb_model.pkl','wb') as files:
    pickle.dump(nb_classifier,files)
with open('svm_model.pkl','wb') as files:
    pickle.dump(svm_classifier,files)