In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

dataset = pd.read_csv("dataset rat full 9f.csv")

In [2]:
dataset.shape

(52842, 10)

# Dataframe processed

In [3]:
# input
x = dataset.iloc[:, [0,1,2,4,5,7,8]].values
  
# output
y = dataset.iloc[:, -1].values


In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state=0)

In [5]:
X_train
# X_train.shape

array([[1.43113377e+00, 3.40000000e+01, 5.25760397e+01, ...,
        1.61100000e+03, 1.37802607e-01, 4.59627329e-02],
       [1.27364403e+00, 3.00000000e+00, 5.06896552e+01, ...,
        2.90000000e+02, 2.17241379e-01, 5.53633218e-02],
       [1.43397469e+00, 8.00000000e+00, 5.16049383e+01, ...,
        8.10000000e+02, 2.70370370e-01, 4.69715698e-02],
       ...,
       [1.53631247e+00, 5.00000000e+00, 4.56989247e+01, ...,
        7.44000000e+02, 3.79032258e-01, 6.32570659e-02],
       [1.34843488e+00, 1.01000000e+02, 5.31195841e+01, ...,
        3.46200000e+03, 6.23050260e-01, 4.39179428e-02],
       [1.58073167e+00, 7.00000000e+00, 4.49218750e+01, ...,
        5.12000000e+02, 1.17187500e-01, 7.63209393e-02]])

In [6]:
X_test
# X_test.shape

array([[1.73449771e+00, 2.53000000e+02, 4.48994022e+01, ...,
        1.55570000e+04, 1.13775149e-02, 6.27410645e-02],
       [1.86068941e+00, 4.80000000e+01, 5.34082923e+01, ...,
        1.42300000e+03, 0.00000000e+00, 3.44585091e-02],
       [1.87239796e+00, 8.00000000e+00, 4.56790123e+01, ...,
        3.24000000e+02, 1.48148148e-01, 8.04953560e-02],
       ...,
       [1.59275450e+00, 8.00000000e+00, 4.73502304e+01, ...,
        8.68000000e+02, 4.76958525e-01, 6.11303345e-02],
       [2.03661129e+00, 7.00000000e+00, 3.51827389e+01, ...,
        2.27100000e+03, 3.83091149e-02, 1.07488987e-01],
       [1.02727891e+00, 4.00000000e+01, 6.11973392e+01, ...,
        9.02000000e+02, 1.99556541e-01, 2.77469478e-02]])

In [7]:
# from sklearn.preprocessing import StandardScaler
# sc_x = StandardScaler()
# X_train = sc_x.fit_transform(X_train) 
# X_test = sc_x.transform(X_test)
  
# print (X_train[0:10, :])

In [8]:
X_train.shape

(39631, 7)

# Logistic Regression model

In [9]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state = 2)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

In [10]:
# from sklearn.model_selection import cross_val_score

# scores = cross_val_score(classifier, x, y, cv=5)
# print("Logistic Regression Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[6162  470]
 [1191 5388]]


In [12]:

from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.8742714404662781


In [13]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)


Test set RMSE: 0.3545822323999355


# Random Forest

In [14]:
from sklearn.ensemble import RandomForestClassifier

random_classifier = RandomForestClassifier(n_estimators=50, random_state=0)
random_classifier.fit(X_train, y_train)

y_pred = random_classifier.predict(X_test)

In [15]:
# from sklearn.model_selection import cross_val_score

# scores = cross_val_score(random_classifier, x, y, cv=5)
# print("Logistic Regression Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

In [16]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[6075  557]
 [ 809 5770]]


In [17]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.896601317084248


In [18]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)


Test set RMSE: 0.32155665584116283


# Support Vector Machine

In [ ]:
from sklearn.svm import SVC

svm_classifier = SVC(kernel='linear', random_state=0)
svm_classifier.fit(X_train, y_train)

y_pred = svm_classifier.predict(X_test)

In [ ]:
# from sklearn.model_selection import cross_val_score

# scores = cross_val_score(svm_classifier, x, y, cv=5)
# print("Logistic Regression Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

In [ ]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

In [ ]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)

# Naive Bayes

In [19]:
from sklearn.naive_bayes import GaussianNB

nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)

y_pred = nb_classifier.predict(X_test)

In [20]:
# from sklearn.model_selection import cross_val_score

# scores = cross_val_score(nb_classifier, x, y, cv=5)
# print("Logistic Regression Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
  
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[6259  373]
 [2352 4227]]


In [22]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.7937324956475664


In [23]:
from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Test set RMSE:', rmse)

Test set RMSE: 0.4541668243635081


# Pickle formation

In [25]:
import pickle


In [26]:

with open('lr_model rat 7f new.pkl','wb') as files:
    pickle.dump(classifier,files)

In [27]:

with open('random_model rat 7f new.pkl','wb') as files:
    pickle.dump(random_classifier,files)

In [28]:

with open('nb_model rat 7f new.pkl','wb') as files:
    pickle.dump(nb_classifier,files)

In [ ]:

with open('svm_model rat 7f new.pkl','wb') as files:
    pickle.dump(svm_classifier,files)